import type { Product, Collection, Occasion } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "gf-001",
    name: "Rashmika Floral Anarkali",
    price: 3499,
    originalPrice: 4999,
    category: "Anarkali",
    occasion: ["festival", "wedding", "party"],
    colors: ["#C0392B", "#8E44AD", "#2980B9"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: "Georgette",
    pattern: "floral",
    description:
      "A stunning full-length anarkali adorned with delicate floral embroidery. Crafted from premium georgette with intricate zari work on the yoke and hem, this piece makes a statement at every festive occasion. Comes with a matching churidar and dupatta.",
    care: "Dry clean only. Store in a breathable garment bag.",
    sku: "GF-ANR-001",
    rating: 4.8,
    reviewCount: 124,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "gf-002",
    name: "Meena Zari Silk Saree",
    price: 6299,
    originalPrice: 8500,
    category: "Saree",
    occasion: ["wedding", "festival", "formal"],
    colors: ["#D4AC0D", "#1A5276", "#A93226"],
    sizes: ["Free Size"],
    fabric: "Pure Silk",
    pattern: "zari",
    description:
      "Timeless Banarasi-inspired silk saree with heavy zari border and pallu. The rich gold weave on deep jewel tones creates a regal look perfect for weddings and festive celebrations. Each piece is handwoven by skilled artisans.",
    care: "Dry clean only. Do not wring or tumble dry.",
    sku: "GF-SAR-002",
    rating: 4.9,
    reviewCount: 89,
    isBestseller: true,
    isFeatured: true,
  },
  {
    id: "gf-003",
    name: "Priya Block Print Kurta Set",
    price: 1899,
    originalPrice: 2499,
    category: "Kurta Set",
    occasion: ["casual", "office", "festival"],
    colors: ["#E8D5C4", "#5D6D7E", "#1E8449"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Cotton",
    pattern: "block",
    description:
      "Breezy cotton kurta set featuring traditional block-print motifs. The three-piece set includes a straight kurta, palazzo pants, and a printed dupatta. Perfect for everyday elegance with a bohemian flair.",
    care: "Machine wash cold, gentle cycle. Dry in shade.",
    sku: "GF-KRT-003",
    rating: 4.6,
    reviewCount: 203,
    isNew: true,
  },
  {
    id: "gf-004",
    name: "Divya Mirror Work Lehenga",
    price: 8999,
    originalPrice: 12000,
    category: "Lehenga",
    occasion: ["wedding", "party", "festival"],
    colors: ["#922B21", "#1A5276", "#1E8449"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Raw Silk",
    pattern: "mirror",
    description:
      "Opulent lehenga choli with intricate mirror work and sequin embellishments. The flared skirt features over 500 hand-set mirrors that catch light beautifully. Comes with a heavily embroidered choli and matching dupatta.",
    care: "Dry clean only. Store flat to prevent mirror damage.",
    sku: "GF-LHG-004",
    rating: 4.7,
    reviewCount: 67,
    isBestseller: true,
  },
  {
    id: "gf-005",
    name: "Sunaina Chanderi Suit",
    price: 2799,
    originalPrice: 3500,
    category: "Suit",
    occasion: ["office", "casual", "festival"],
    colors: ["#F0E6D3", "#7D6608", "#117A65"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    fabric: "Chanderi",
    pattern: "floral",
    description:
      "Elegant Chanderi silk suit with fine floral embroidery on the neckline and cuffs. The lightweight fabric drapes beautifully making it ideal for long days at the office or casual outings. Includes an unstitched salwar piece.",
    care: "Hand wash in cold water with mild detergent.",
    sku: "GF-SUT-005",
    rating: 4.5,
    reviewCount: 156,
  },
  {
    id: "gf-006",
    name: "Kavya Palazzo Set",
    price: 1599,
    category: "Palazzo Set",
    occasion: ["casual", "beach", "party"],
    colors: ["#F1948A", "#82E0AA", "#85C1E9"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Rayon",
    pattern: "block",
    description:
      "Vibrant rayon palazzo set with bold block-print patterns. The relaxed fit palazzo paired with a crop top makes a contemporary style statement. Comfortable enough for day-long wear, stylish enough for evening outings.",
    care: "Machine wash cold. Iron on medium heat.",
    sku: "GF-PAL-006",
    rating: 4.4,
    reviewCount: 178,
    isNew: true,
  },
  {
    id: "gf-007",
    name: "Ananya Embroidered Dupatta",
    price: 899,
    originalPrice: 1200,
    category: "Dupatta",
    occasion: ["wedding", "festival", "formal"],
    colors: ["#F9E79F", "#FDEBD0", "#D5F5E3"],
    sizes: ["Free Size"],
    fabric: "Chiffon",
    pattern: "zari",
    description:
      "Luxurious chiffon dupatta with heavy zari embroidery on all four borders. The delicate fabric with golden thread work adds grace to any outfit. A versatile piece that elevates even a simple kurta.",
    care: "Dry clean only. Handle with care.",
    sku: "GF-DUP-007",
    rating: 4.6,
    reviewCount: 92,
    isBestseller: true,
  },
  {
    id: "gf-008",
    name: "Ishita Bandhani Gown",
    price: 4299,
    originalPrice: 5500,
    category: "Gown",
    occasion: ["party", "wedding", "festival"],
    colors: ["#C0392B", "#8E44AD", "#F39C12"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Georgette",
    pattern: "mirror",
    description:
      "Contemporary floor-length gown featuring traditional Bandhani tie-dye technique with modern mirror work accents. The flowy georgette creates a dreamy silhouette perfect for destination weddings and cocktail parties.",
    care: "Dry clean recommended. Machine wash cold on delicate cycle.",
    sku: "GF-GWN-008",
    rating: 4.7,
    reviewCount: 53,
    isNew: true,
    isFeatured: true,
  },
  // ---------- NEW PRODUCTS ----------
  {
    id: "gf-009",
    name: "Naina Embroidered Sharara Set",
    price: 3999,
    originalPrice: 5200,
    category: "Sharara Set",
    occasion: ["wedding", "festival", "party"],
    colors: ["#9B59B6", "#F39C12", "#E74C3C"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: "Net",
    pattern: "floral",
    description:
      "Exquisite net sharara set with heavily embroidered kurta and flared sharara pants. The intricate threadwork on the neckline and hemline makes it a perfect choice for festive celebrations and mehndi ceremonies.",
    care: "Dry clean only. Store in muslin cloth.",
    sku: "GF-SHR-009",
    rating: 4.7,
    reviewCount: 88,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "gf-010",
    name: "Kajal Printed Kaftan",
    price: 1299,
    originalPrice: 1799,
    category: "Kaftan",
    occasion: ["casual", "beach", "party"],
    colors: ["#F0B27A", "#76D7C4", "#F1948A"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    fabric: "Rayon",
    pattern: "block",
    description:
      "Flowy rayon kaftan with vibrant block-print motifs. Loose and breezy, ideal for beach holidays, casual brunches, or relaxed evenings at home. Pair with statement earrings for an effortless boho look.",
    care: "Machine wash cold, gentle cycle. Dry flat.",
    sku: "GF-KFT-010",
    rating: 4.3,
    reviewCount: 142,
    isNew: true,
  },
  {
    id: "gf-011",
    name: "Riya Ikkat Silk Saree",
    price: 4899,
    originalPrice: 6500,
    category: "Saree",
    occasion: ["office", "wedding", "formal"],
    colors: ["#E74C3C", "#2C3E50", "#1E8449"],
    sizes: ["Free Size"],
    fabric: "Silk",
    pattern: "geometric",
    description:
      "Handloom Ikkat silk saree with striking geometric patterns woven using the resist-dyeing technique. The bold palette and structured drape give a confident, polished look for office wear and formal events.",
    care: "Dry clean only. Iron on silk setting.",
    sku: "GF-SAR-011",
    rating: 4.8,
    reviewCount: 61,
    isBestseller: true,
  },
  {
    id: "gf-012",
    name: "Sonal Chikankari Kurti",
    price: 1499,
    originalPrice: 2000,
    category: "Kurti",
    occasion: ["casual", "office"],
    colors: ["#FDFEFE", "#D5DBDB", "#A9CCE3"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: "Cotton",
    pattern: "chikankari",
    description:
      "Classic Lucknowi Chikankari kurti with delicate hand-embroidered white threadwork on soft cotton fabric. Breathable and elegant — perfect for summer office days or relaxed outings. Pairs beautifully with churidar or palazzo pants.",
    care: "Hand wash in cold water. Dry in shade.",
    sku: "GF-KRT-012",
    rating: 4.6,
    reviewCount: 219,
    isBestseller: true,
  },
  {
    id: "gf-013",
    name: "Pooja Tissue Lehenga",
    price: 12500,
    originalPrice: 16000,
    category: "Lehenga",
    occasion: ["wedding", "festival"],
    colors: ["#D4AC0D", "#CB4335", "#1F618D"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Tissue Silk",
    pattern: "zari",
    description:
      "Bridal-grade tissue silk lehenga with all-over zari butti and a heavily embroidered border. The iridescent shimmer of tissue fabric makes every step magical. Comes with a matching choli and organza dupatta with scalloped edges.",
    care: "Dry clean only. Store in acid-free tissue paper.",
    sku: "GF-LHG-013",
    rating: 4.9,
    reviewCount: 34,
    isFeatured: true,
  },
  {
    id: "gf-014",
    name: "Meghna Georgette Palazzo Set",
    price: 2299,
    originalPrice: 2999,
    category: "Palazzo Set",
    occasion: ["office", "casual", "party"],
    colors: ["#1ABC9C", "#884EA0", "#E67E22"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    fabric: "Georgette",
    pattern: "solid",
    description:
      "Smart georgette palazzo set with a self-print kurta top and wide-leg pants. The flowing silhouette keeps you comfortable and stylish through long office hours or evening outings. Minimal embroidery at the neckline adds a refined touch.",
    care: "Machine wash cold, gentle cycle. Iron on low.",
    sku: "GF-PAL-014",
    rating: 4.4,
    reviewCount: 107,
  },
  {
    id: "gf-015",
    name: "Heena Phulkari Dupatta",
    price: 1199,
    originalPrice: 1600,
    category: "Dupatta",
    occasion: ["festival", "wedding", "casual"],
    colors: ["#E74C3C", "#F39C12", "#27AE60"],
    sizes: ["Free Size"],
    fabric: "Silk",
    pattern: "floral",
    description:
      "Vibrant Punjabi Phulkari dupatta with dense floral embroidery on a rich silk base. The riot of colours makes it a statement accessory over a simple kurta or suit. Handcrafted by artisans from Punjab.",
    care: "Dry clean only. Handle gently to preserve threadwork.",
    sku: "GF-DUP-015",
    rating: 4.7,
    reviewCount: 73,
    isNew: true,
  },
  {
    id: "gf-016",
    name: "Tara Organza Festive Suit",
    price: 5499,
    originalPrice: 7000,
    category: "Suit",
    occasion: ["festival", "wedding", "party"],
    colors: ["#F9E79F", "#F8C471", "#FDFEFE"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Organza",
    pattern: "floral",
    description:
      "Dreamy organza suit with sequin-embellished floral motifs that catch every glimmer of light. The semi-sheer fabric layers beautifully with a silk inner lining. An ideal choice for Navratri garba nights or upscale festive dinners.",
    care: "Dry clean only. Store away from direct sunlight.",
    sku: "GF-SUT-016",
    rating: 4.8,
    reviewCount: 49,
    isFeatured: true,
  },
  {
    id: "gf-017",
    name: "Deepa Linen Coord Set",
    price: 1799,
    originalPrice: 2400,
    category: "Coord Set",
    occasion: ["casual", "office"],
    colors: ["#BFC9CA", "#5D6D7E", "#784212"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: "Linen",
    pattern: "solid",
    description:
      "Minimalist linen coord set featuring a straight kurta and tapered pants. The breathable linen keeps you cool while the clean-cut silhouette projects quiet confidence at the office or weekend brunches.",
    care: "Machine wash cold. Iron while slightly damp for best results.",
    sku: "GF-CRD-017",
    rating: 4.5,
    reviewCount: 168,
    isNew: true,
  },
  {
    id: "gf-018",
    name: "Lakshmi Kanjivaram Saree",
    price: 9999,
    originalPrice: 14000,
    category: "Saree",
    occasion: ["wedding", "formal", "festival"],
    colors: ["#C0392B", "#D4AC0D", "#1A5276"],
    sizes: ["Free Size"],
    fabric: "Kanjivaram Silk",
    pattern: "zari",
    description:
      "Heritage Kanjivaram silk saree with traditional temple-border motifs and a rich contrasting pallu. Hand-woven with real zari thread, this heirloom-quality piece is the ultimate choice for weddings, grihapravesh, and religious ceremonies.",
    care: "Dry clean only. Store with silica packets in a silk saree cover.",
    sku: "GF-SAR-018",
    rating: 4.9,
    reviewCount: 28,
    isBestseller: true,
    isFeatured: true,
  },
  {
    id: "gf-019",
    name: "Swara Cotton Anarkali",
    price: 1699,
    originalPrice: 2200,
    category: "Anarkali",
    occasion: ["casual", "festival", "office"],
    colors: ["#7DCEA0", "#F1948A", "#F9E79F"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: "Cotton",
    pattern: "block",
    description:
      "Lightweight cotton anarkali with bold block-print patterns and a comfortable A-line silhouette. The midi length and relaxed fit make it your go-to for long festive days when you want to look good without compromising comfort.",
    care: "Machine wash cold. Dry in shade. Iron on medium.",
    sku: "GF-ANR-019",
    rating: 4.5,
    reviewCount: 193,
    isNew: true,
  },
  {
    id: "gf-020",
    name: "Brinda Velvet Blouse",
    price: 1999,
    originalPrice: 2800,
    category: "Blouse",
    occasion: ["wedding", "party", "festival"],
    colors: ["#922B21", "#1F618D", "#1E8449"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Velvet",
    pattern: "solid",
    description:
      "Statement velvet saree blouse with intricate gold hand-embroidery on the back and sleeves. The plush fabric and tailored fit give any saree an instant bridal upgrade. Available in deep jewel tones for a luxe festive look.",
    care: "Dry clean only. Do not iron directly on velvet.",
    sku: "GF-BLS-020",
    rating: 4.6,
    reviewCount: 56,
    isBestseller: true,
  },
];

export const COLLECTIONS: Collection[] = [
  {
    id: "col-festive",
    name: "Festive Edit",
    tagline: "Celebrate in colour",
    accent: "var(--g-gold-500)",
  },
  {
    id: "col-wedding",
    name: "Bridal Trousseau",
    tagline: "Your forever looks",
    accent: "var(--g-rose-600)",
  },
  {
    id: "col-everyday",
    name: "Everyday Chic",
    tagline: "Effortless ethnic",
    accent: "var(--g-ink-600)",
  },
];

export const OCCASIONS: Occasion[] = [
  { id: "wedding", name: "Wedding", emoji: "💍" },
  { id: "festival", name: "Festival", emoji: "🪔" },
  { id: "party", name: "Party", emoji: "✨" },
  { id: "office", name: "Office", emoji: "💼" },
  { id: "casual", name: "Casual", emoji: "☀️" },
  { id: "beach", name: "Beach", emoji: "🏖️" },
  { id: "formal", name: "Formal", emoji: "🎩" },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductsByOccasion(occasion: string): Product[] {
  return PRODUCTS.filter((p) => p.occasion.includes(occasion));
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.isFeatured);
}

export function getNewArrivals(): Product[] {
  return PRODUCTS.filter((p) => p.isNew);
}

export function getBestsellers(): Product[] {
  return PRODUCTS.filter((p) => p.isBestseller);
}

export function fmtINR(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}
